swagger: "2.0"
info:
    description: A brief description of the "Have I been pwned?" k-Anonymity API
    version: "1.0.0"
    title: Have I Been Pwned
    termsOfService: "https://haveibeenpwned.com/API/v2#AcceptableUse"
    license:
        name: Creative Commons Attribution 4.0 International License
        url: "https://haveibeenpwned.com/API/v2#License"
host: api.pwnedpasswords.com
basePath: "/"
schemes:
- https
paths:
    /range/{prefix}:
        get:
            summary: Search for exposed hashes
            description: Search for exposed hases
            operationId: range
            produces:
            - "*/*"
            parameters:
            - name: prefix
              in: path
              description: First 5 hex chars of a SHA1 hash
              required: true
              type: string
              minLength: 5
              maxLength: 5
            responses:
                200:
                    description: OK
                    schema:
                        type: string
                429:
                    description: Rate Limit
