// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRangeParams creates a new RangeParams object
// with the default values initialized.
func NewRangeParams() *RangeParams {
	var ()
	return &RangeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRangeParamsWithTimeout creates a new RangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRangeParamsWithTimeout(timeout time.Duration) *RangeParams {
	var ()
	return &RangeParams{

		timeout: timeout,
	}
}

// NewRangeParamsWithContext creates a new RangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewRangeParamsWithContext(ctx context.Context) *RangeParams {
	var ()
	return &RangeParams{

		Context: ctx,
	}
}

// NewRangeParamsWithHTTPClient creates a new RangeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRangeParamsWithHTTPClient(client *http.Client) *RangeParams {
	var ()
	return &RangeParams{
		HTTPClient: client,
	}
}

/*RangeParams contains all the parameters to send to the API endpoint
for the range operation typically these are written to a http.Request
*/
type RangeParams struct {

	/*Prefix
	  First 5 hex chars of a SHA1 hash

	*/
	Prefix string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the range params
func (o *RangeParams) WithTimeout(timeout time.Duration) *RangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the range params
func (o *RangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the range params
func (o *RangeParams) WithContext(ctx context.Context) *RangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the range params
func (o *RangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the range params
func (o *RangeParams) WithHTTPClient(client *http.Client) *RangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the range params
func (o *RangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPrefix adds the prefix to the range params
func (o *RangeParams) WithPrefix(prefix string) *RangeParams {
	o.SetPrefix(prefix)
	return o
}

// SetPrefix adds the prefix to the range params
func (o *RangeParams) SetPrefix(prefix string) {
	o.Prefix = prefix
}

// WriteToRequest writes these params to a swagger request
func (o *RangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param prefix
	if err := r.SetPathParam("prefix", o.Prefix); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
